config/routes.rb
Billcue::Application.routes.draw do
  devise_for :users

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  root :to => 'calendar#index'

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController

  def index
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = Event.event_strips_for_month(@shown_month)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  #def routing
    #render '/public/404'
  #end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   respond_to :html

  # GET /artists/new
  def new
    @event = Event.new
    respond_with(@event)
  end 

  def show
    @event = Event.find(params[:id])
    respond_with(@event)
  end

  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save!
        format.html { redirect_to(root_path, :notice => 'Your event was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/calendar/index.html.haml
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
- stylesheet_link_tag "event_calendar"
#header-container
  %h1#header Calendar 

%p
  = link_to 'Add New Event', new_event_path, :class => 'lbOn'

= raw(event_calendar)

app/views/events/_new.html.haml
- form_for(@event) do |f|
  = f.label :name
  = f.text_field :name
  %p
    = f.label :start_at
    = f.date_select :start_at

  %p
    = f.label :end_at
    = f.date_select :end_at

  %p
    = f.submit 'Create', :class => 'lbAction', :rel => 'deactivate'

= button_to 'Close Window', '#', :class => 'lbAction', :rel => 'deactivate'

app/views/events/new.html.haml
%h2 Add New Bill

= render :partial => 'new'

app/views/events/show.html.haml
%h1
  = @event.name

%h4
  Price:

%h4
  #{ @event.start_at.to_s(:due) }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Billcue</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>